//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, ExistsArgs as $ExistsArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type ShortenedUrlFindManyArgs = $FindManyArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlFindUniqueArgs = $FindUniqueArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlFindFirstArgs = $FindFirstArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlExistsArgs = $ExistsArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlCreateArgs = $CreateArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlCreateManyArgs = $CreateManyArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlUpdateArgs = $UpdateArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlUpdateManyArgs = $UpdateManyArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlUpsertArgs = $UpsertArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlDeleteArgs = $DeleteArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlDeleteManyArgs = $DeleteManyArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlCountArgs = $CountArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlAggregateArgs = $AggregateArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlGroupByArgs = $GroupByArgs<$Schema, "ShortenedUrl">;
export type ShortenedUrlWhereInput = $WhereInput<$Schema, "ShortenedUrl">;
export type ShortenedUrlSelect = $SelectInput<$Schema, "ShortenedUrl">;
export type ShortenedUrlInclude = $IncludeInput<$Schema, "ShortenedUrl">;
export type ShortenedUrlOmit = $OmitInput<$Schema, "ShortenedUrl">;
export type ShortenedUrlGetPayload<Args extends $SelectIncludeOmit<$Schema, "ShortenedUrl", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "ShortenedUrl", Args, Options>;
