//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
/**
 * 短縮URLモデル
 * ビルドデータの長いURLを短いコードに変換して保存
 */
export type ShortenedUrl = $ModelResult<$Schema, "ShortenedUrl">;
