//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        ShortenedUrl: {
            name: "ShortenedUrl",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                code: {
                    name: "code",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                originalUrl: {
                    name: "originalUrl",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                }
            },
            attributes: [
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("code")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                code: { type: "String" },
                originalUrl: { type: "String" }
            }
        }
    } as const;
    plugins = {};
}
export const schema = new SchemaType();
